# Generated by Django 4.2.16 on 2024-09-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_top",
            field=models.BooleanField(default=False),
        ),
    ]
