# Generated by Django 4.2.16 on 2024-09-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_article_is_top"),
    ]

    operations = [
        migrations.AddField(
            model_name="article", name="views", field=models.IntegerField(default=0),
        ),
    ]
